### ISSUE TITLE
Not compile on gcc 7.3.1

### ISSUE THREAD

**Issue by Pro-pra** [felixdoerre/primus_vk#12]
`g++ -std=gnu++11 -g3 -I/usr/include/vulkan -shared -fPIC primus_vk.cpp -o libprimus_vk.so
primus_vk.cpp: In constructor 'Fence::Fence(VkDevice)':
primus_vk.cpp:261:13: sorry, unimplemented: non-trivial designated initializers not supported
     .flags=0};
             ^
primus_vk.cpp: In constructor 'Semaphore::Semaphore(VkDevice)':
primus_vk.cpp:278:94: sorry, unimplemented: non-trivial designated initializers not supported
 reateInfo semInfo = {.sType=VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO, .flags=0};
                                                                              ^
primus_vk.cpp: In constructor 'CommandBuffer::CommandBuffer(VkDevice)':
primus_vk.cpp:449:172: sorry, unimplemented: non-trivial designated initializers not supported
 flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT, .queueFamilyIndex = 0 };
                                                                              ^
primus_vk.cpp:449:172: sorry, unimplemented: non-trivial designated initializers not supported
primus_vk.cpp:451:199: sorry, unimplemented: non-trivial designated initializers not supported
 =commandPool, .level=VK_COMMAND_BUFFER_LEVEL_PRIMARY, .commandBufferCount = 1};
                                                                              ^
primus_vk.cpp:451:199: sorry, unimplemented: non-trivial designated initializers not supported
primus_vk.cpp:451:199: sorry, unimplemented: non-trivial designated initializers not supported
Makefile:7: recipe for target 'libprimus_vk.so' failed
make: *** [libprimus_vk.so] Error 1`

**Comment by felixdoerre** [comment]
Yes, the code uses non-trivial designated initializers. Together with @leonmaxx you convinced me to not use them for now. So please update to current master. It should compile now.

**Comment by Pro-pra** [comment]
thank you.

**Comment by Pro-pra** [comment]
also i add to primus_vk.cpp
`#include vk_layer_dispatch_table.h`

**Comment by leonmaxx** [comment]
Still have one at [primus_vk_diag.cpp:183](https://github.com/felixdoerre/primus_vk/blob/c85dc5a7b55427eb9f208beef7770a7ea003f256/primus_vk_diag.cpp#L183).

**Comment by felixdoerre** [comment]
Yes, that slipped. I've corrected it. Thank you very much.

**Comment by leonmaxx** [comment]
Hello again.
```
primus_vk.cpp: In function 'VkResult PrimusVK_CreateInstance(const VkInstanceCreateInfo*, const VkAllocationCallbacks*, VkInstance_T**)':
primus_vk.cpp:181:139: sorry, unimplemented: non-trivial designated initializers not supported
     instance_info[GetKey(*pInstance)] = InstanceInfo{.instance = *pInstance, .render = render, .display=display, .secondarySpawned = false};
                                                                                                                                           ^
```

**Comment by felixdoerre** [comment]
Done, see f00873e
