### ISSUE TITLE
Expand this to other GPU configurations

### ISSUE THREAD

**Issue by boberfly** [felixdoerre/primus_vk#14]
Hi @felixdoerre 

I'm just experimenting here with some tests where I changed the integrated/discrete check to locate my display (Nvidia Quadro k2000) and pair it with my offload card (Vega FE) via vendorID checks (eg. 0x10de and 0x1002). I think I might be running into the deadlock problem that you mentioned as it prints that out and I just get a black screen with vkcubepp.

Anyways I was wondering what your opinion is on this as that would be an amazing feature to have, at least for me.

Cheers

**Comment by felixdoerre** [comment]
The only problem that I see with this usecase would be that I see no way how to auto-detect such a situation. I see no problem to add an environment variable that allows to force the device selection.
Would that be a good option for you?

Regarding the deadlock: The issue I opened against Vulkan-Loader does not seem to get any attention by the maintainers there, so I still don't have a really better idea than using e.g. gdb to pause the game thread in the right position until device creation is done, or writing a library that wraps the whole loader `libvulkan-*.so` from the application.

**Comment by boberfly** [comment]
Hi @felixdoerre 

Yeah I don't mind just passing ID as an environment variable to get this to work. It's more so I can do vulkan development or offloading like playing DXVK on the beefier GPU but display it on the weaker one, much like [Looking Glass](https://looking-glass.hostfission.com/) only it is just the same Linux host.

I'm not sure if it is deadlocking here, but it certainly doesn't display anything from the other card onto the display one here when I activate Primus...

**Comment by felixdoerre** [comment]
I've also added a small hint in README.md for the environment variables. Thank's again for your PR. I that solves this issue.
