### ISSUE TITLE
Please be more verbose when the nvidia driver cant be load

### ISSUE THREAD

**Issue by Thaodan** [felixdoerre/primus_vk#19]
see title.

**Comment by felixdoerre** [comment]
Should the layer explicitly look for setup issues (i.e. manually parse json files and look for common mistakes)? There is currently not really more information available in such a situation.

**Comment by Thaodan** [comment]
I thought of something like error loading the nvidia driver instead of displaying a version mismatch.

**Comment by felixdoerre** [comment]
The error message:
> ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: ICD libnv_vulkan_wrapper.so doesn't support interface version compatible with loader, skip this ICD.
Is not printed by primus_vk but by the loader. Maybe the wrapper could detect such a version mismatch and report it accordingly, but I currently don't know how vulkan version negotiation works and how to detect and report a version mismatch better.

**Comment by Thaodan** [comment]
This message is posted when libGL cant be found during the loading of the wrapper.
Maybe this message should reflect that if possible.

**Comment by felixdoerre** [comment]
So maybe something to stderr from here?

https://github.com/felixdoerre/primus_vk/blob/master/nv_vulkan_wrapper.cpp#L30

**Comment by Thaodan** [comment]
yeah.
