### ISSUE TITLE
Issue starting vulkan application

### ISSUE THREAD

**Issue by nephitejnf** [felixdoerre/primus_vk#20]
I'm trying to run vkQuake with the `pvkrun` script from the primus-vk-git AUR package. It seems to see the proper card and recognize the vulkan layers, but it always errors out. zsh claims a segmentation fault. vkQuake runs fine without using the pvkrun script because it'll run on the intel card instead. I do have the vulkan-validation-layers package installed as well.

When I run it with `PRIMUS_VK_MULTITHREADING=1 VK_LOADER_DEBUG=all` I get `ERROR: terminator_CreateDevice: Failed in ICD libGLX_nvidia.so.0 vkCreateDevicecall` at the end.

He is the log for the first case.
https://pastebin.com/QQn0qmi8

**Comment by nephitejnf** [comment]
I removed it and I still get the same thing...

**Comment by felixdoerre** [comment]
I've just uploaded an extension to the "primus_vk_diag.cpp" tool so it also creates a device (as this is where it seems to crash on your system). Can you compile it and run `primus_vk_diag.sh` and paste the output? If this is a driver issue it would be good to have a minimal reproducing example with with we can further test..

**Comment by nephitejnf** [comment]
This is what I got on output, it was too big for pastebin.
https://paste.ee/p/JRa48

**Comment by nephitejnf** [comment]
Yeah, in order to open up the nvidia-settings I have to direct it to display `:8` and I can get games like Half-Life to recognize the NVIDIA card, but those run OpenGL.

**Comment by nephitejnf** [comment]
I saw there were some slight changes to the code and re ran the diag after rebuilding.

https://paste.ee/p/U5cd0

**Comment by felixdoerre** [comment]
Do you run `primus_vk_diag.sh` with `ENABLE_PRIMUS_LAYER=1`? That's not intended, It's intended that `primus_vk_diag.sh` sets for some tests but not for all. I've updated `primus_vk_diag.sh` to ensure this. Can you update and re-run diag?

**Comment by nephitejnf** [comment]
Oops, forgot about that detail. I corrected it now.
https://paste.ee/p/YNnWg

**Comment by felixdoerre** [comment]
The output shows the same problem: Even the wrapper can't get the nvidia driver to work. For primus-vk to work, the underlying vulkan needs to list both GPUs. You can quickly verify that by using `optirun ./primus_vk_diag vulkan` (without `ENABLE_PRIMUS_LAYER`). From the diag output, this does not list the dedicated GPU on your system. It seems that the hack from here https://github.com/felixdoerre/primus_vk/blob/master/nv_vulkan_wrapper.cpp#L73 does not work on your system. Could you also post the output of `optirun env DISPLAY=:8 ./primus_vk_diag vulkan` to see if generally an environment-variable setting-hack could get the nvidia driver to start?

**Comment by nephitejnf** [comment]
This is what I get from them both...
https://paste.ee/p/wAIEt

**Comment by felixdoerre** [comment]
Thanks. That confirms the theory that the nvidia driver on your system refuses to load. I've pushed adjusted code for the nv_wrapper on https://github.com/felixdoerre/primus_vk/tree/nv_wrapper_experimental Could you compile that code, replace your `/usr/lib/libnv_vulkan_wrapper.so` and re-run `./primus_vk_diag vulkan` and `optirun env DISPLAY=:8 ./primus_vk_diag vulkan` and send the output?

**Comment by nephitejnf** [comment]
This is my output.
https://paste.ee/p/Sj0P3

**Comment by jonpas** [comment]
Ideally there would be 2 AUR packages (64 and 32-bit). I am willing to comaintain the AUR packages with @Thaodan.

**Comment by leonmaxx** [comment]
The one I posted should be a good start for 32-bit one.

**Comment by leonmaxx** [comment]
> First problem is that this AUR package doesn't disable NVidia's ICD JSON (rename it or whatever), without this PrimusVK might use **NVidia ICD directly** instead of Primus-Vk wrapper.

That is probably why Nvidia driver uses X display `:0`.

**Comment by leonmaxx** [comment]
@nephitejnf Can you try to rename (or move them somewhere else) NVidia's JSON files found by command:
```
find /etc/vulkan/icd.d/ /usr/share/vulkan/icd.d/ -name "nvidia_icd*.json" -type f
```
And then re-test?

**Comment by felixdoerre** [comment]
@leonmaxx The nvidia driver will not start unless `DISPLAY=:8` is set. We cannot set `DISPLAY=:8` globally, as the game must see `DISPLAY=:0` to start its windows and stuff on the correct display. The problem here is that the Nvidia driver can twice be not convinced (not with wrapper and of course not without) to use Display `:8`. So even the wrapper doesn't seem to help.

@nephitejnf Thanks for the new output. It confirms that the nvidia driver on your system decides to look up `$DISPLAY` when the hack does not override it. I've added more tracing and already a few guesses of what could help the nvidia driver on your load. Could you please repeat the last test with the updated wrapper from `nv_wrapper_experimental`?

**Comment by leonmaxx** [comment]
@felixdoerre Let @nephitejnf try my suggestion, I'm sure it'll work after he removes Nvidia ICDs.

**Comment by felixdoerre** [comment]
:-) aah... I think I understand what's happening: when the unwrapped nvidia driver is loaded it sees the wrong `$DISPLAY`. The wrapped nvidia driver does not re-load the shared library but is linked against the same instance, which already has cached the wrong `$DISPLAY`. This causes the wrapped library to fail as well.

**Comment by leonmaxx** [comment]
@felixdoerre If wrapped driver ever loaded in this case.

**Comment by felixdoerre** [comment]
It is, at least that's what it says in the log, a few times:
```
    20423:	calling init: /usr/lib/libnv_vulkan_wrapper.so
```

**Comment by leonmaxx** [comment]
It's Vulkan Loaders log entry?
Is it possible that Primus-Vk layer happens to select unwrapped driver as renderer?

**Comment by felixdoerre** [comment]
That line is from `primus_vk_diag` with `LD_DEBUG=libs`. Is it possible that Primus-Vk layer happens to select unwrapped driver as renderer? No. The drivers don't initialize enough to be able to be selected as renderer. The PhysicalDevice doesn't even show up. From the layer's perpective there is no working nvidia driver installed / no nvidia device existing.

**Comment by felixdoerre** [comment]
Great! Thanks @leonmaxx for the solution.

**Comment by nephitejnf** [comment]
I guess that would be another not to make for Arch users is to remove nvidia's icd and then possibly try to make a change in the pkgbuild for both the `primus-vk-git` and `lib32-primus-vk-git`, but yes, thanks for all your help.
