### ISSUE TITLE
Unable to link primus_vk_diag.o

### ISSUE THREAD

**Issue by jonpas** [felixdoerre/primus_vk#21]
Unsure what I am missing to compile primus_vk_diag, but below is the log. Must be something simple I am missing.

```
$ make primus_vk_diag
g++ -std=gnu++11 -g3 -DNV_DRIVER_PATH=/usr/lib/libGLX_nvidia.so.0   -c -o primus_vk_diag.o primus_vk_diag.cpp
cc   primus_vk_diag.o   -o primus_vk_diag
/usr/bin/ld: primus_vk_diag.o: in function `VulkanContext::VulkanContext()':
/home/jonpas/Work/Other/primus_vk/primus_vk_diag.cpp:59: undefined reference to `std::cout'
/usr/bin/ld: /home/jonpas/Work/Other/primus_vk/primus_vk_diag.cpp:59: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
... more undefined references like ...
```

I am trying to run this to diagnose an issue I have with this project, which seems to be using the wrong GPU for rendering (iGPU instead of dGPU). Removing intel ICD only prevents even `vulkaninfo` from showing GPU data. Anyways, that's another issue that I will create if I can't figure out what's going on after diag run.

**Comment by felixdoerre** [comment]
try `make primus-vk-diag` with minuses. Yes, I guess that make target is named a bit misleadingly.

**Comment by jonpas** [comment]
Oh, :laughing: I knew it was something stupid. I'll PR a change.
