### ISSUE TITLE
New error with DXVK version 1.0.

### ISSUE THREAD

**Issue by leonmaxx** [felixdoerre/primus_vk#26]
When trying to run World Of Tanks with DXVK 1.0 log is flooded with:
```
PrimusVK: Error, fence in acquireNextImage not implemented
```
Game window is unresponsive.

**Comment by felixdoerre** [comment]
Yes, that particular feature was not implemented. Could you try https://github.com/felixdoerre/primus_vk/tree/try_acquire_fence ?

**Comment by leonmaxx** [comment]
Sure, will test later today.

**Comment by leonmaxx** [comment]
Sorry, had almost no free time these days. I tested suggested branch and it seems to work ok.
