### ISSUE TITLE
Create proper releases

### ISSUE THREAD

**Issue by grazzolini** [felixdoerre/primus_vk#33]
Hi @felixdoerre. First of all, let me thank you for this amazing software. I have been using primus_vk for a while now and it works perfectly.

I'm an Arch Linux developer and I want to include primus_vk on the official repositories. But, for doing that I would need actual tagged releases. There are some packages that are built from git on official repos and that tag an specific commit or cherrypick a few of them to make a release, see systemd [0] and xf86-video-intel [1] for examples.

Currently primus_vk has two packages on Arch Linux user repository, primus-vk-git [2] and it's 32-bit counterpart [3].

Even though I can probably introduce an official package using similar conditions, it would be nice to have a proper tagged (and possibly signed) release to refer to. This aids specially when reporting bugs.

Thanks in advance.

[0] https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/systemd
[1] https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/xf86-video-intel
[2] https://aur.archlinux.org/packages/primus-vk-git/
[3] https://aur.archlinux.org/packages/lib32-primus-vk-git/

**Comment by felixdoerre** [comment]
Like this? https://github.com/felixdoerre/primus_vk/releases/tag/v1.0
Thanks for creating an official package! Please let me know if I can be of any other help.

**Comment by grazzolini** [comment]
Hi @felixdoerre, that's perfect, thanks. I'm going to use this release 1.0 as the initial release for a package. Also, I'm going to name the package as primus_vk and not primus-vk as the AUR package does on git.

You can consider as well, in the future, signing the releases. I should have this package today on the official repositories.

**Comment by felixdoerre** [comment]
Is the signature on v1.0 usable or did I do something wrong?

**Comment by grazzolini** [comment]
No, the semantic versioning here is not the issue. What I meant was adding a PGP signature of the release as well. But this is not required right now.

**Comment by felixdoerre** [comment]
I should have signed v1.0 with the gpg key FD4066F7DB7D993F

**Comment by grazzolini** [comment]
I see that your commits are signed already, which is good. In this case all that is left is to put a detached signature of the source.zip and source.tar.gz files. Also, the package is live already: https://www.archlinux.org/packages/community/x86_64/primus_vk/

Please, check the PKGBUILD with the instructions to build it and see if you disagree with anything:

**Comment by felixdoerre** [comment]
Why don't you use the same functions for downloading as the systemd package and benefit from the signed commit?
```
validpgpkeys('0A9D381479E6D19CE365E301FD4066F7DB7D993F')
source=("git+https://github.com/felixdoerre/primus_vk#tag=v${pkgver}?signed")
sha512sums=('SKIP')
```

**Comment by grazzolini** [comment]
Hey @felixdoerre, I can switch to a signed commit package in a future release. But, it doesn't preclude the need for releases. On another note, can you please take a look at the first comment here on the [AUR git package](https://aur.archlinux.org/packages/primus-vk-git/)?

I can run pvkrun vulkaninfo from a terminal just fine. And it is working from steam as well. But I was able to get at least one instance of running a game with pvkrun where it would not work if all ICD's weren't present. Do you think pvkrun needs patching?

**Comment by felixdoerre** [comment]
Hmm... That patch is essentially taking the whole icd-discovery out of the vulkan loader and into `pvkrun` in a modified and vastly simplified way. The loader searches various different directories as well: https://github.com/KhronosGroup/Vulkan-Loader/blob/1df2ebd329df1ece1a5ed485573ea58e5bc6ff97/loader/loader.c#L3729

So when you have both icd-files (the original for the 'plain' nvidia driver and the wrapped), you are dependent on the order of files returned by `opendir`.

Assuming that `SYSCONFDIR` is configued as `/etc` and `EXTRASYSCONFDIR` as `/usr/share`, it would be cleaner to install the primus_vk wrapper-icd into `/etc/vulkan/icd.d` when the original nvidia icd is installed in `/usr/share/icd.d`. That should ensure the proper loading order and seems less of a hack to me.

Another option is to delete/move the nvidia icd.d file from `/usr/share/vulkan/icd.d`, but I am not sure how easy/hacky that is.

What option from those three would you consider the best?

**Comment by grazzolini** [comment]
Never mind. It turns out that lutris was forcing an icd, and was loading only the nv_vulkan_wrapper.json. Which would obviously make it not load the intel icd. If I change the configuration to not search for any specific icd, it is working. I'm closing this issue. Thanks again @felixdoerre. I'll change the package later to use signed commits.
