### ISSUE TITLE
How to see PrimusVK log entries?

### ISSUE THREAD

**Issue by ellogwen** [felixdoerre/primus_vk#39]
I can successfully run vulkan applications with either ENABLE_PRIMUS_LAYER primusrun or pvkrun but I do not see PrimusVK log entries like other people shown. Do I need a special flag to enable the PrimusVK info/warn/error logs?

**Comment by felixdoerre** [comment]
No, there are no special flags. These messages are always printed to standard out. You can try with `vkcube` and should see the debug messages in the console. For most games I run I can easily see all debug messages. For now I didn't implement tracing to a file as e.g. dxvk does it.

**Comment by felixdoerre** [comment]
Were you able to see the log messages? As you didn't reply again, I assume that the issue is solved.
