### ISSUE TITLE
Inability to play the game after alt + tab (to return to desktop) in KDE

### ISSUE THREAD

**Issue by edoantonioco** [felixdoerre/primus_vk#40]
Hello. So Im in KDE, and when I am playing a game I can alt+tab to the desktop and do something else, and after that I can return to the game and keep playing.

This applyes to opengl games running through bumblebee. But with this tool (maybe its just an issue with vulkan itself) when you do that, and attemp to return to the game, it either crashes or freeze the screen so you have to kill the process.

**Comment by felixdoerre** [comment]
I think this issue is very likely game-specific. All games that I play with primus_vk ca be tabbed in and out with no problems at all. Did you try other games?

**Comment by edoantonioco** [comment]
this in manjaro, I tried Zed (a recent unreal engine 4 game), and also mad max in vulkan mode, and it happen on both. Have yet to try on any other game

**Comment by leonmaxx** [comment]
Try to disable full-screen unredirect in system settings, this may solve Alt+Tab issue. In KDE it's in `Display and Monitor -> Compositor`:
![fs_unredirect](https://user-images.githubusercontent.com/12882831/59660706-e80e4900-91b1-11e9-8a2a-9cc9aec83548.png)

**Comment by felixdoerre** [comment]
This issue needs game specific information for debugging. On top of that, current `HEAD` contains handling of an environment variable `PVK_SUPPRESS_SUBOPTIMAL` that can be used to work around games doing strange things when they find out their swapchain should be re-created, and lying to them to keep the swapchain as-is.
