### ISSUE TITLE
Portage of primus_vk for Gentoo Linux 

### ISSUE THREAD

**Issue by jaypeche** [felixdoerre/primus_vk#45]
Support of Vulkan API Layer for bumblebee on Gentoo GNU/Linux.

* Latest ebuild revision : https://ftp.pingwho.org/pub/gentoo/ftp/overlay/dbox2-overlay/x11-libs/primus_vk/
* Compilation logs :  https://gist.github.com/jaypeche/818116a7ee88eddd8ca2e21215ff9e16

**Comment by felixdoerre** [comment]
Thank you! Can I include any installation instructions based on that in the Readme?

**Comment by jaypeche** [comment]
# Gentoo Linux integration :

The ebuild requires an overlay branch to integrate seamlessly into Portage.
If you have not done so already, modify /etc/portage/make.conf like this:


`# mkdir -p usr/local/portage/x11-libs/primus_vk/files`
`# nano /etc/portage/make.conf`

PORTDIR_OVERLAY is a directory where local ebuilds may be stored without
concern that they will be deleted by rsync updates. Default is not
defined.

PORTDIR_OVERLAY="/usr/local/portage"

`# cd /usr/local/portage/x11-libs/primus_vk/files`
`# wget -c https://ftp.pingwho.org/pub/gentoo/ftp/overlay/dbox2-overlay/x11-libs/primus_vk/files/primus_vk_gentoo_fix.diff`
`# cd ..`
`# wget -c https://ftp.pingwho.org/pub/gentoo/ftp/overlay/dbox2-overlay/x11-libs/primus_vk/primus_vk-1.1-r1.ebuild`
`# wget -c https://ftp.pingwho.org/pub/gentoo/ftp/overlay/dbox2-overlay/x11-libs/primus_vk/metadata.xml`
`# wget -c https://ftp.pingwho.org/pub/gentoo/ftp/overlay/dbox2-overlay/x11-libs/primus_vk/ChangeLog`
`# ebuild primus_vk-1.1-r1.ebuild digest`
`# emerge -av primus_vk`
