### ISSUE TITLE
rainbow-colored speckles on wayland

### ISSUE THREAD

**Issue by greyltc** [felixdoerre/primus_vk#52]
I've got this working fine (besides some screen tearing/vsync issues) on my Arch laptop with an Intel GPU and a GeForce GTX 960M. I ended up having to launch like this to get it to work properly though:
```bash
ENABLE_PRIMUS_LAYER=1 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nv_vulkan_wrapper.json:/usr/share/vulkan/icd.d/intel_icd.x86_64.json optirun ${THING_TO_RUN}
```
When I use it under gnome-shell on wayland the DX11 & proton-4.11.3-based thing I'm launching ends up having rainbow-colored speckles all over it (though the performance seems fine). When I switch gnome to run on X and repeat the same thing, the speckles are gone and everything seems to work fine.

Any idea how to fix that?

**Comment by felixdoerre** [comment]
No, I didn't find time to test and debug this myself. I assume, it's the same problem as #32. So far we've established that the artifacts appear to be created after the image is copied by primus_vk (and before it's rendered on the the screen). However I don't know yet what component is misbehaving.

**Comment by greyltc** [comment]
Yes. Same issue, sorry for the dupe!

**Comment by felixdoerre** [comment]
No problem. The title of that other issue is not really descriptive :).

**Comment by felixdoerre** [comment]
I've improved the title of the other issue and close this one as duplicate.
