### ISSUE TITLE
Game issue with lutris

### ISSUE THREAD

**Issue by Daglas69** [felixdoerre/primus_vk#54]
Hello, I have a problem trying to use primus_vk for world of warcraft with lutris. I am on fedora 30.

I installed primus_vk and set up the game configuration settings as:
Optimus launcher: primus vk
Vulkan ICD loader: Auto(Default) -in the first test-
Vulkan ICD loader: primus_vk_wrapper.json -in the second test-

So in the first case, the launcher and game both launch but the display looks really weird ...
(take a look at the the test1*.png pictures and test1-log.txt)

And in the second case, the launcher launch well but I have an error starting the game (3d accelerator card not supported, test2*.png and test2-log.txt)

I don't know where the error comes from... 
Do you have an idea ?

(sorry for my bad english)

![test1_game-display](https://user-images.githubusercontent.com/28512258/66088296-3caab980-e540-11e9-9486-ae4ae3471867.png)
![test1_game-settings](https://user-images.githubusercontent.com/28512258/66088297-3caab980-e540-11e9-84aa-dc596967932c.png)
[test1-log.txt](https://github.com/felixdoerre/primus_vk/files/3683762/test1-log.txt)
![test2_game-error](https://user-images.githubusercontent.com/28512258/66088298-3d435000-e540-11e9-8ae1-ad9a8ef7bb57.png)
![test2_game-settings](https://user-images.githubusercontent.com/28512258/66088299-3d435000-e540-11e9-8754-f8471886af4c.png)
[test2-log.txt](https://github.com/felixdoerre/primus_vk/files/3683763/test2-log.txt)

**Comment by Daglas69** [comment]
Now I can launch the game with the game config 
Optimus launcher: primus vk
Vulkan ICD loader: Auto(Default)

without the weird display in the launcher, but still weird in the game ... And I don't know why the launcher looks good now...

**Comment by felixdoerre** [comment]
Do you have the latest code? ( i.e. is e3c4f6cebe30823a85ea4b4c6514d2858bd52d53 included?). These artifacts look a lot like those, that were fixed in that commit. So you need that code version (or just take current master) and you need it compiled for 32 and for 64 bit (I assume the launcher is a 32-bit executable and the game is a 64-bit executable).

So, are you sure, that you have the latest version of primus_vk in both 32 and 64 bit?

**Comment by felixdoerre** [comment]
As for the two "test scenarios":

> Vulkan ICD loader: Auto(Default) -in the first test-
> Vulkan ICD loader: primus_vk_wrapper.json -in the second test-

the "first test" is the way that primus_vk should work. The second is expected to fail (we need the the intel icd and the primus_vk_wrapped-nvidia icd, so primus_vk can interact with both drivers)

**Comment by Daglas69** [comment]
I finally decided to use prime on my nvidia gpu so I don't have this problem no more.

I installed primus_vk from another repository with rpm so I assume that it would be better to install it manually from git.
