### ISSUE TITLE
GTA V using proton and DXVK does not run

### ISSUE THREAD

**Issue by appetterson** [felixdoerre/primus_vk#7]
I have set up primus_vk on Arch Linux using the modifications discussed in this issue #5.
Arch Linux does not ship vulkan-smoketest, but I am able to run vulkan-info and vk-cube with my 960m using optirun (I have ENABLE_PRIMUS_LAYER=1 set in my profile).

optirun vulkaninfo does give an error after printing out the expected information:
`/build/vulkan-tools/src/Vulkan-Tools/vulkaninfo/vulkaninfo.c:3618: failed with VK_ERROR_INITIALIZATION_FAILED`
Though vkcube seems to run without any problems

Adding optirun to the games in Steam's launch options seems to have no effect however, and they act simply as they do without primus_vk. The games I have tried are No Man's Sky and Grand Theft Auto 5 (the latter using the fix described here https://github.com/ValveSoftware/Proton/issues/37#issuecomment-415833819). In the case of No Man's Sky the game simply does not launch, with Grand Theft Auto 5 the launcher works but complains about missing DirectX runtimes. Both games launch when using nvidia-xrun in a different tty.

My laptop has a 960m with an intel i7-6700HQ. My current versions are:
nvidia 410.57-1
dxvk 0.80-2
bumblebee 3.2.1-19
primus 20151110-7
mesa 18.2.1-2
vulkan-intel 18.2.1-2
nvidia-utils 410.57-1
lib32-nvidia-utils 410.57-1

I removed the 32 bit intel vulkan driver as this seemed to be causing some issues in vulkaninfo.

Apologies if I missed something that means this shouldn't work yet but I've reread the readme and the issues several times and found nothing.

**Comment by felixdoerre** [comment]
So through Proton you don't get stdout from the games? So it probably might be best if I change the tracing code to write to a file, so we get at least some debugging info.
Have you tried running `primus_vk_diag.sh`? This script tries different scenarios of OpenGL/Vulkan usage and tries thereby if all graphics drivers are behaving as they should. Could you run that script and attach the output?

**Comment by felixdoerre** [comment]
Additionally, you could try the trick that came up in https://github.com/felixdoerre/primus_vk/issues/6#issuecomment-425756080, when the game creates more than one `VkInstance` at the same time the code currently can't cope with that. Disabling that return could be a way to get the game running.

**Comment by appetterson** [comment]
> Additionally, you could try the trick that came up in [#6 (comment)](https://github.com/felixdoerre/primus_vk/issues/6#issuecomment-425756080), when the game creates more than one `VkInstance` at the same time the code currently can't cope with that. Disabling that return could be a way to get the game running.

This seems to have done the trick! I had to use primusrun rather than optirun in both cases. Performance in GTA5 was very poor, I guess this is possibly a related issue to #6. No Man's Sky ran smooth though, maybe a slight performance hit from nvidia-xrun but nothing unplayable! I believe No Man's Sky uses Vulkan rather than DirectX, so there is no DXVK in the middle, so that could be the difference?

Thanks for the help and good job getting this working! :)

**Comment by felixdoerre** [comment]
The performance hit comes from games doing work in the mainloop where presenting is invoked. As I was lazy and implemented the image-transfer synchronously, this puts additional work in the mainloop which then causes the game to run slowly. So I think that its simply the way how the game was written and not directly related to DXVK.

**Comment by felixdoerre** [comment]
Hi, as mentioned in #6 I have just pushed a performance improvement, that could possibly also solve the problem you're facing. Could you also update and try again?

**Comment by appetterson** [comment]
Performance has massively improved. Managed to get a 3 star wanted level and escape it in GTA5 which certainly would not have been possible before! Performance is probably on par with nvidia-xrun. Thanks for this! :)

**Comment by felixdoerre** [comment]
Great, that the games you try are now playable. I just pushed a fix to master that should address the second problem, that primus_vk cannot handle applications that request multiple `VkInstance` objects. So the current master should work with games, that previously required commenting out the error check (in fact there is no error check anymore).
Can you please update to master and try if that change works for you?

**Comment by appetterson** [comment]
I can confirm that it works without making those change. Only changes I made to the code for this commit was the arch specific changes as mentioned in #5 (adding vk_layer_utils.h and changing the library to libGLX_nvidia.so.0). Games seem to be running at around 24-26 fps. Thanks for the update!

**Comment by felixdoerre** [comment]
On: Why does primus_vk call libvuikan_intel.so:

It works as does the primus for opengl. It uses the nvidia/dedicated driver to render and the intel/integrated driver to display. So: it has to interact with both.

On: How do you make GTA5 run using this? I don't have this game, but i think you you should use `optirun` in your Steam launch command instead of `primusrun`. Did you try that?

**Comment by minecraft2048** [comment]
I give up and use nvidia-xrun instead for my primary desktop, anyway everywhere I go there's always a power outlet so battery is not a concern

**Comment by jonpas** [comment]
Testing on "Ori and the Blind Forest: Defintive Edition" and seem to be having a similar problem. Can't get `primus_vk` to run on my dGPU. DXVK HUD shows iGPU (unless what is written in the HUD is not the actual renderer card?) and very low FPS confirms that.

Tried with `optirun`, `optirun -b primus` and `primusrun` through Steam's Proton. `vkcube` runs fine though, shows my dGPU as renderer and iGPU as display. I will run diag in the coming days and add that here.

Is there anything I am missing or other information I should supply to help diagnose this?

**Comment by felixdoerre** [comment]
Your issue probably has nothing to do with what's discussed in this issue. Ori is a 32-bit game, which means it uses a 32-bit vulkan to communicate with 32-bit drivers and a 32-bit primus-vk. The Makefile currently doesn't compile for 32 bit. So I assume you'll need to make a 32-bit wrapper, and a 32-bit layer and install them both properly. So far I have not seen any "general proton" issue of primus-vk. It was always a game-specific issue.

**Comment by jonpas** [comment]
Oh, I see, sorry for hijacking the issue then!

I will work on 32-bit compiling and wrapper and layer and open a PR if I make it work.

**Comment by leonmaxx** [comment]
Just adding `-m32` flag to compile and link commands is enough, that is the way I package Primus-Vk RPMs.

**Comment by jonpas** [comment]
I got it to work, thanks @leonmaxx!

I will possibly make some PRs in the coming weeks. In the meantime, is there a chat channel you use?

**Comment by grazzolini** [comment]
@jonpas, Arch now has an official package for primus_vk: https://www.archlinux.org/packages/community/x86_64/primus_vk/

I'm using primus_vk to run GTA 5 just by using pvkrun %command% on steam, it works with good performance.

I'm now creating a lib32-primus_vk package, based on the existing one on the AUR: https://aur.archlinux.org/packages/lib32-primus-vk-git/

**Comment by jonpas** [comment]
Yep I noticed! And that's great, thanks for doing this!

**Comment by grazzolini** [comment]
The package is up: https://www.archlinux.org/packages/multilib/x86_64/lib32-primus_vk/

**Comment by felixdoerre** [comment]
Is there anything left, that primus_vk can do here, or can we close the issue?

**Comment by Arucard1983** [comment]
Instead GTA V, Assassin's Creed III that happens to use Intel HD Vulkan driver from Debian 9.
In fact it require to build the 32-bit versions of primus_vk, using the steps at:
https://github.com/felixdoerre/primus_vk/issues/7#issuecomment-456543653

**Comment by felixdoerre** [comment]
So as it all works now, I close the issue.
