### ISSUE TITLE
libprimus_vk.so problem

### ISSUE THREAD

**Issue by andjeozla** [felixdoerre/primus_vk#70]
$ sudo make libprimus_vk.so
g++  --std=gnu++11 -g3 -I/usr/include/vulkan -shared -fPIC primus_vk.cpp -o libprimus_vk.so -Wl,-soname,libprimus_vk.so.1 -ldl -lpthread 
In file included from primus_vk.cpp:4:
/usr/include/vulkan/vulkan.h:48:10: fatal error: wayland-client.h: No such file or directory
 #include <wayland-client.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: libprimus_vk.so] Error 1

This is mistake I get when trying to compile libprimus. I am on MX linux, can you help me?

Thanks.

**Comment by felixdoerre** [comment]
Is your desktop running on wayland or in X11? I assume that it is not wayland. To resolve this compile problem, you can either install the libwayland headers. I have no idea what packages exist in MX linux and how to search for them, but in debian, the package is called `libwayland-dev`. 

The other option is to compile primus-vk without wayland support. You can do this, by deleting this line locally: https://github.com/felixdoerre/primus_vk/blob/f84fba6d2b5820e91e75bebb5b91cbed6cde00da/primus_vk.cpp#L3

Does this answer your question?

**Comment by andjeozla** [comment]
g++  --std=gnu++11 -g3 -I/usr/include/vulkan -shared -fPIC primus_vk.cpp -o libprimus_vk.so -Wl,-soname,libprimus_vk.so.1 -ldl -lpthread 
In file included from primus_vk.cpp:4:
/usr/include/vulkan/vulkan.h:60:10: fatal error: xcb/xcb.h: No such file or directory
 #include <xcb/xcb.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: libprimus_vk.so] Error 1

Now this error. Will try without wayland

Thanks for the reply.

**Comment by felixdoerre** [comment]
So you found `libwayland-dev`? This is good. The problem, you are seeing now is the same story for xcb. This is probaby more important, as this is now required for X11 windows. The missing headers are probably in  `libxcb1-dev`. And just to save us the thrid roundtrip: you willl also need `libx11-dev` for another kind oft X11-windows.

**Comment by andjeozla** [comment]
make libprimus_vk.so
g++  --std=gnu++11 -g3 -I/usr/include/vulkan -shared -fPIC primus_vk.cpp -o libprimus_vk.so -Wl,-soname,libprimus_vk.so.1 -ldl -lpthread 
primus_vk.cpp:7:10: fatal error: vk_layer_dispatch_table.h: No such file or directory
 #include "vk_layer_dispatch_table.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: libprimus_vk.so] Error 1


Managed to duckduckgo that now i have this.

**Comment by felixdoerre** [comment]
Do you know that you can search for debian packages by filename that is included? This one is probably in `vulkan-validationlayers-dev`. On [this page](https://www.debian.org/distrib/packages) in the last search form, is you search for `vk_layer_dispatch_table.h`, you can find the containing package (`vulkan-validationlayer-dev`). I hope the debian package names help you.

**Comment by andjeozla** [comment]
make libprimus_vk.so
g++  --std=gnu++11 -g3 -I/usr/include/vulkan -shared -fPIC primus_vk.cpp -o libprimus_vk.so -Wl,-soname,libprimus_vk.so.1 -ldl -lpthread 
primus_vk.cpp:69:3: error: ‘PFN_vkLayerCreateDevice’ does not name a type; did you mean ‘PFN_vkCreateDevice’?
   PFN_vkLayerCreateDevice layerCreateDevice;
   ^~~~~~~~~~~~~~~~~~~~~~~
   PFN_vkCreateDevice
primus_vk.cpp:70:3: error: ‘PFN_vkLayerDestroyDevice’ does not name a type; did you mean ‘PFN_vkDestroyDevice’?
   PFN_vkLayerDestroyDevice layerDestroyDevice;
   ^~~~~~~~~~~~~~~~~~~~~~~~
   PFN_vkDestroyDevice
primus_vk.cpp:83:9: error: ‘PFN_vkLayerCreateDevice’ has not been declared
         PFN_vkLayerCreateDevice layerCreateDevice,
         ^~~~~~~~~~~~~~~~~~~~~~~
primus_vk.cpp:84:9: error: ‘PFN_vkLayerDestroyDevice’ has not been declared
         PFN_vkLayerDestroyDevice layerDestroyDevice) : instance(instance), layerCreateDevice(layerCreateDevice), layerDestroyDevice(layerDestroyDevice) {
         ^~~~~~~~~~~~~~~~~~~~~~~~
primus_vk.cpp: In constructor ‘InstanceInfo::InstanceInfo(VkInstance, int, int)’:
primus_vk.cpp:84:76: error: class ‘InstanceInfo’ does not have any field named ‘layerCreateDevice’
         PFN_vkLayerDestroyDevice layerDestroyDevice) : instance(instance), layerCreateDevice(layerCreateDevice), layerDestroyDevice(layerDestroyDevice) {
                                                                            ^~~~~~~~~~~~~~~~~
primus_vk.cpp:84:114: error: class ‘InstanceInfo’ does not have any field named ‘layerDestroyDevice’
 yDevice layerDestroyDevice) : instance(instance), layerCreateDevice(layerCreateDevice), layerDestroyDevice(layerDestroyDevice) {
                                                                                         ^~~~~~~~~~~~~~~~~~

primus_vk.cpp: In function ‘VkResult PrimusVK_CreateInstance(const VkInstanceCreateInfo*, const VkAllocationCallbacks*, VkInstance_T**)’:
primus_vk.cpp:244:3: error: ‘PFN_vkLayerCreateDevice’ was not declared in this scope
   PFN_vkLayerCreateDevice layerCreateDevice = nullptr;
   ^~~~~~~~~~~~~~~~~~~~~~~
primus_vk.cpp:244:3: note: suggested alternative: ‘PFN_vkCreateDevice’
   PFN_vkLayerCreateDevice layerCreateDevice = nullptr;
   ^~~~~~~~~~~~~~~~~~~~~~~
   PFN_vkCreateDevice
primus_vk.cpp:245:3: error: ‘PFN_vkLayerDestroyDevice’ was not declared in this scope
   PFN_vkLayerDestroyDevice layerDestroyDevice = nullptr;
   ^~~~~~~~~~~~~~~~~~~~~~~~
primus_vk.cpp:245:3: note: suggested alternative: ‘PFN_vkDestroyDevice’
   PFN_vkLayerDestroyDevice layerDestroyDevice = nullptr;
   ^~~~~~~~~~~~~~~~~~~~~~~~
   PFN_vkDestroyDevice
primus_vk.cpp:252:115: error: ‘VK_LOADER_LAYER_CREATE_DEVICE_CALLBACK’ was not declared in this scope
 sType == VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO &&  layerCreateInfo->function == VK_LOADER_LAYER_CREATE_DEVICE_CALLBACK) {
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

primus_vk.cpp:252:115: note: suggested alternative: ‘VK_LOADER_DATA_CALLBACK’
 sType == VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO &&  layerCreateInfo->function == VK_LOADER_LAYER_CREATE_DEVICE_CALLBACK) {
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                         VK_LOADER_DATA_CALLBACK
primus_vk.cpp:253:7: error: ‘layerCreateDevice’ was not declared in this scope
       layerCreateDevice = layerCreateInfo->u.layerDevice.pfnLayerCreateDevice;
       ^~~~~~~~~~~~~~~~~
primus_vk.cpp:253:7: note: suggested alternative: ‘vkCreateDevice’
       layerCreateDevice = layerCreateInfo->u.layerDevice.pfnLayerCreateDevice;
       ^~~~~~~~~~~~~~~~~
       vkCreateDevice
primus_vk.cpp:253:46: error: ‘union VkLayerInstanceCreateInfo::<unnamed>’ has no member named ‘layerDevice’
       layerCreateDevice = layerCreateInfo->u.layerDevice.pfnLayerCreateDevice;
                                              ^~~~~~~~~~~
primus_vk.cpp:254:7: error: ‘layerDestroyDevice’ was not declared in this scope
       layerDestroyDevice = layerCreateInfo->u.layerDevice.pfnLayerDestroyDevice;
       ^~~~~~~~~~~~~~~~~~
primus_vk.cpp:254:7: note: suggested alternative: ‘vkDestroyDevice’
       layerDestroyDevice = layerCreateInfo->u.layerDevice.pfnLayerDestroyDevice;
       ^~~~~~~~~~~~~~~~~~
       vkDestroyDevice
primus_vk.cpp:254:47: error: ‘union VkLayerInstanceCreateInfo::<unnamed>’ has no member named ‘layerDevice’
       layerDestroyDevice = layerCreateInfo->u.layerDevice.pfnLayerDestroyDevice;
                                               ^~~~~~~~~~~
primus_vk.cpp:262:6: error: ‘layerCreateDevice’ was not declared in this scope
   if(layerCreateDevice == nullptr || layerDestroyDevice == nullptr) {
      ^~~~~~~~~~~~~~~~~
primus_vk.cpp:262:6: note: suggested alternative: ‘vkCreateDevice’
   if(layerCreateDevice == nullptr || layerDestroyDevice == nullptr) {
      ^~~~~~~~~~~~~~~~~
      vkCreateDevice
primus_vk.cpp:262:38: error: ‘layerDestroyDevice’ was not declared in this scope
   if(layerCreateDevice == nullptr || layerDestroyDevice == nullptr) {
                                      ^~~~~~~~~~~~~~~~~~
primus_vk.cpp:262:38: note: suggested alternative: ‘vkDestroyDevice’
   if(layerCreateDevice == nullptr || layerDestroyDevice == nullptr) {
                                      ^~~~~~~~~~~~~~~~~~
                                      vkDestroyDevice
primus_vk.cpp:284:52: error: ‘layerCreateDevice’ was not declared in this scope
   auto my_instance_info = InstanceInfo{*pInstance, layerCreateDevice, layerDestroyDevice};
                                                    ^~~~~~~~~~~~~~~~~
primus_vk.cpp:284:52: note: suggested alternative: ‘vkCreateDevice’
   auto my_instance_info = InstanceInfo{*pInstance, layerCreateDevice, layerDestroyDevice};
                                                    ^~~~~~~~~~~~~~~~~
                                                    vkCreateDevice
primus_vk.cpp:284:71: error: ‘layerDestroyDevice’ was not declared in this scope
   auto my_instance_info = InstanceInfo{*pInstance, layerCreateDevice, layerDestroyDevice};
                                                                       ^~~~~~~~~~~~~~~~~~
primus_vk.cpp:284:71: note: suggested alternative: ‘vkDestroyDevice’
   auto my_instance_info = InstanceInfo{*pInstance, layerCreateDevice, layerDestroyDevice};
                                                                       ^~~~~~~~~~~~~~~~~~
                                                                       vkDestroyDevice
primus_vk.cpp:284:89: error: no matching function for call to ‘InstanceInfo::InstanceInfo(<brace-enclosed initializer list>)’
   auto my_instance_info = InstanceInfo{*pInstance, layerCreateDevice, layerDestroyDevice};
                                                                                         ^
primus_vk.cpp:82:3: note: candidate: ‘InstanceInfo::InstanceInfo(VkInstance, int, int)’
   InstanceInfo(VkInstance instance,
   ^~~~~~~~~~~~
primus_vk.cpp:82:3: note:   conversion of argument 2 would be ill-formed:
primus_vk.cpp:81:3: note: candidate: ‘InstanceInfo::InstanceInfo(InstanceInfo&&)’
   InstanceInfo(InstanceInfo &&) = default;
   ^~~~~~~~~~~~
primus_vk.cpp:81:3: note:   candidate expects 1 argument, 3 provided
primus_vk.cpp:79:3: note: candidate: ‘InstanceInfo::InstanceInfo()’
   InstanceInfo() = default;
   ^~~~~~~~~~~~
primus_vk.cpp:79:3: note:   candidate expects 0 arguments, 3 provided
primus_vk.cpp: In function ‘VkResult PrimusVK_CreateDevice(VkPhysicalDevice, const VkDeviceCreateInfo*, const VkAllocationCallbacks*, VkDevice_T**)’:
primus_vk.cpp:748:40: error: ‘struct InstanceInfo’ has no member named ‘layerCreateDevice’
   auto createDevice = my_instance_info.layerCreateDevice;
                                        ^~~~~~~~~~~~~~~~~
primus_vk.cpp: In lambda function:
primus_vk.cpp:751:16: error: ‘createDevice’ is not captured
     auto ret = createDevice(my_instance_info.instance, my_instance_info.display, &createInfo, nullptr, &dev, PrimusVK_GetInstanceProcAddr, &gdpa);
                ^~~~~~~~~~~~
primus_vk.cpp:749:46: note: the lambda has no capture-default
   cod->finish([createDevice,&my_instance_info](VkDeviceCreateInfo &createInfo, VkDevice &dev){
                                              ^
primus_vk.cpp:748:8: note: ‘<typeprefixerror>createDevice’ declared here
   auto createDevice = my_instance_info.layerCreateDevice;
        ^~~~~~~~~~~~
primus_vk.cpp:757:12: error: unable to deduce lambda return type from ‘ret’
     return ret;
            ^~~
primus_vk.cpp: In function ‘VkResult PrimusVK_CreateDevice(VkPhysicalDevice, const VkDeviceCreateInfo*, const VkAllocationCallbacks*, VkDevice_T**)’:
primus_vk.cpp:758:4: error: no matching function for call to ‘CreateOtherDevice::finish(PrimusVK_CreateDevice(VkPhysicalDevice, const VkDeviceCreateInfo*, const VkAllocationCallbacks*, VkDevice_T**)::<lambda(VkDeviceCreateInfo&, VkDevice_T*&)>)’
   });
    ^
primus_vk.cpp:557:8: note: candidate: ‘void CreateOtherDevice::finish(std::function<VkResult(VkDeviceCreateInfo&, VkDevice_T*&)>)’
   void finish(std::function<VkResult(VkDeviceCreateInfo &createInfo, VkDevice &dev)> creator){
        ^~~~~~
primus_vk.cpp:557:8: note:   no known conversion for argument 1 from ‘PrimusVK_CreateDevice(VkPhysicalDevice, const VkDeviceCreateInfo*, const VkAllocationCallbacks*, VkDevice_T**)::<lambda(VkDeviceCreateInfo&, VkDevice_T*&)>’ to ‘std::function<VkResult(VkDeviceCreateInfo&, VkDevice_T*&)>’
primus_vk.cpp: In function ‘void PrimusVK_DestroyDevice(VkDevice, const VkAllocationCallbacks*)’:
primus_vk.cpp:842:15: error: ‘struct InstanceInfo’ has no member named ‘layerDestroyDevice’
   my_instance.layerDestroyDevice(display_device, nullptr, device_dispatch[GetKey(display_device)].DestroyDevice);
               ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:19: libprimus_vk.so] Error 1


Now this is huge. Didn't know that. Working as sys admin at firm that was mostly Microsoft/windows based. About a year and a half we gotten linux based solutions for some security stuff. It's on MX ergo why MX. So I am newbie to this stuff.

**Comment by felixdoerre** [comment]
Ok, this problem looks like your libvulkan-dev is too old. As noted in the README.md, you require at least libvulkan `>= 1.1.108`. I am not really sure, what you can do about this. You can try primus_vk version `1.1` which has a crude workaround to be compatible with libvulkan `< 1.1.108` or you could try to find a way to upgrade your libvulkan. However as I don't really know how things work in MX linux so I can't really help you with that.

**Comment by andjeozla** [comment]
Went with MX ahs (advanced hardware support) in the end. That solved all the problems. Thanks for all the help.

**Comment by felixdoerre** [comment]
Aah ok, that had a newer libvulkan? Or did it even have a packaged primus-vk? It would be interesting to add a few instructions to the readme for other mx-linux users. Do you have some lines, you would suggest?

**Comment by andjeozla** [comment]
Had to tinker it for myself, because it has two packages, primus-vk and primus-nvidia. Primus-nvidia makes it work. Just checked install recommended in MX Package Installer and everything works fine. Also had to go with nvidia-440 which is in testing area of MX. Stable goes with 418. If you don't need vulkan you have to go with option optirun, for vulkan use pvkrun. For some reason it cannot support both ordinary primus and primus-vk. Considering that I need vulkan for gaming/lutris, that's fine by me.

**Comment by cevantes** [comment]
> Ok, this problem looks like your libvulkan-dev is too old. As noted in the README.md, you require at least libvulkan `>= 1.1.108`. I am not really sure, what you can do about this. You can try primus_vk version `1.1` which has a crude workaround to be compatible with libvulkan `< 1.1.108` or you could try to find a way to upgrade your libvulkan.

Thank you for this note, I went with debian bullseye which has newer vulkan and even primus-vk.

**Comment by felixdoerre** [comment]
>  For some reason it cannot support both ordinary primus and primus-vk. Considering that I need vulkan for gaming/lutris, that's fine by me.
This should not be the case: `pvkrun` should work for OpenGL as well as for vulkan (as it internally just calls optirun). So I think `pvkrun` should be a "strict improvement". Just out of curiosity: which primus-vk version is the package that you installed? And where do you experience the conflict? Two packages that refuse being installed together, or where does the conflict between primus and primus-vk show?

On Debian bullseye, the optirun (and primusrun) were patched to also activate primus-vk (if installed). So on a current bullseye installation you should be able to run OpenGL and Vulkan applications with any of the three starters (`optirun`, `primusrun` and `pvkrun`) and it should work in any combination, given that the `primus-vk` (or `primus-vk-nvidia`) package is installed.

**Comment by andjeozla** [comment]
If i install primus it removes libnv-vulkan-wrapper1 libnvidia-glvkspirv. That causes pvkrun to stop/ bash: pvkrun: command not found.

**Comment by felixdoerre** [comment]
Thanks for the info. So it seems that mx-linux picked the packages from debian/ubuntu, that should theoretically work (I think, that I have used them on my computer for some time together and they worked fine). However, if primusrun does not work, that is not that bad, as `pvkrun` and `optirun` should both allow to offload OpenGL applications. Maybe this gets better when the next round with primus_vk 1.5 hits mxlinux. As all problems seem resolved now, I close the issue. Please reopen or open a new one if problems persist or new problems arise.
