### ISSUE TITLE
steam disk write error

### ISSUE THREAD

**Issue by 3bdoo-ba** [felixdoerre/primus_vk#87]
so one of my friends have a problem that when download his games he got the disk write error message and i tried a lot of solution and it didn't work please if you can just type some solutions to see it

**Comment by felixdoerre** [comment]
I don't know this error message and I don't see how this is connected to primus_vk, and this is far too few information to be able to help you. Some basic questions:
Are you using primus_vk? Are you running steam with primus_vk? Does the same problem appear when you don't use primus_vk to run steam? (You can still run individual games with primus_vk while running steam without it)

Regarding the error: Does steam write something to stdout? What is the full error message? (Is the disk full?) Does `dmesg` show more diagnostic info? What file system are you using?...

**Comment by 3bdoo-ba** [comment]
actually i am new to github and i don't know where to fix my problem about the message it's appear after like every 2gb of downloading or sometimes as soon as it's start downloading and i think the problem not a hardware it's software problem because when we try to download another apps from another app (epic games) and it's work so the problem it's from steam we try to repair library folder and it's also didn't work we run steam as administrator and it didn't work if you have another solutions please help me and thank you
![Screenshot 2020-12-24 120642](https://user-images.githubusercontent.com/74665290/103077266-89b0fa80-45e0-11eb-9637-cd1f3d0260e3.jpg)

**Comment by felixdoerre** [comment]
You've left many of my questions unanswered, but to me this seems to be a steam problem and not a primus_vk problem (which you still haven't confirmed using). Are you on a windows system? Issues for the steam client itself should be reported directly to Valve, as this repository is only for issues regarding primus_vk.

**Comment by 3bdoo-ba** [comment]
Actually I don't what's the primus_vk 
But I understand that the issue i have to ask in another place please csn you tell me who can help in github because i am very new to thus website

**Comment by felixdoerre** [comment]
I believe there is not way to report problems with steam for windows on github. You probably need to directly contact steam support. Maybe somewhere from here: https://help.steampowered.com
