### ISSUE TITLE
Test new nvidia driver acquiring logic on dual-nvidia systems

### ISSUE THREAD

**Issue by felixdoerre** [felixdoerre/primus_vk#89]
Hi @jonpas,
Do you still use the 2-Nvidia-Card system and do you still use primus_vk? If so, would you mind testing the latest change in the nv_vulkan_wrapper (29e966e). I needed to make this change to make the driver work with games that use the vulkan driver in a multi-threaded way. The "external" interface that I used before has some logic for thread-switching which is missing in the "internal" interface that we changed to. Can you quickly verify that the new nv_vulkan_wrapper still works with 2 Nvidia cards? I very strongly believe that it should work.

**Comment by jonpas** [comment]
I switched out for an RX 550 on the host a week ago, so sadly not. If I find some time in the near future, I can quickly swap it out and give it a try though. Right now I haven't even setup primus_vk for the new host GPU, very limited time at the moment.

**Comment by felixdoerre** [comment]
Alright, it was anyway just a "blind try" :).
