### ISSUE TITLE
RPM packaging scripts.

### ISSUE THREAD

**Issue by leonmaxx** [felixdoerre/primus_vk#9]
I developed RPM packaging scripts for Primus-vk.
Link to repository: [primus-vk-rpm](https://github.com/leonmaxx/primus-vk-rpm)

It's all-in-one solution that installs libraries and configures them to ready-to-use state.
In releases section there is today's build. Tested with vulkan-smoketest demo.

**Comment by felixdoerre** [comment]
Thanks you very much! I think `crashfix.patch` and `makefile.patch` could be integrated pretty much as-is here as well. I'd also put the driver_path into a preprocessor constant that could be defined to the current value if it does not exist, that could make packaging easier for you.

You also seem to need `libGLX` instead of `libGL` which only caused problems for me (especially when the game would simultaneously load `libGL` through OpenGL-primus). I am not sure whether letting `ld` resolve `libGLX` is a good idea, however OpenGL-primus does not seem to interact with that library so it might be ok.

**Comment by felixdoerre** [comment]
`gcc32bit.patch` could be adopted by using `VK_NULL_HANDLE` (which would be semantically more correct and is already defined to be `0`) instead of `nullptr`.

**Comment by leonmaxx** [comment]
I updated `gcc32bit.patch` with Your suggested changes. After You merge some of the patches I'll update packaging scripts.

**Comment by leonmaxx** [comment]
> I am not sure whether letting `ld` resolve `libGLX` is a good idea

It seems to work better this way:
* Without optirun - ld fails to find this lib and with `crashfix.patch` vulkan loader just skips libnv_vulkan_wrapper.so and then uses Intel's driver (i.e. we don't break vulkan w/o optirun).
* With optirun (adds path of nvidia libs to LD_LIBRARY_PATH) - ld finds lib and uses it.

**Comment by leonmaxx** [comment]
Also, please add a link to my [repo](https://github.com/leonmaxx/primus-vk-rpm) in Readme.

**Comment by felixdoerre** [comment]
regarding the non-absolute `ld` path: That's essentially the issue I described in the README.md as number 4. However it may work for this instance, as there is no second libGLX in `LD_LIBRARY_PATH`. You can try compiling `primus-vk-diag` and run e.g. `optirun ./primus-vk-diag vulkan gl vulkan` (or `gl vulkan gl`). I had a game that has that initializing behavior and wrote this diag utility to simulate that behavior. You can try that.

Anyhow, I pushed a few commits that integrate some of the patches from your repo and added a link in the Readme. Does this resolve this issue?

**Comment by leonmaxx** [comment]
> Does this resolve this issue?

Yes, thanks. You can close it or leave it open for further discussion.
I'll update packaging scripts in the evening.

**Comment by leonmaxx** [comment]
> You can try compiling `primus-vk-diag` and run e.g. `optirun ./primus-vk-diag vulkan gl vulkan` (or `gl vulkan gl`).

Looks like all is ok:
```
$ optirun primus-vk-diag vulkan gl vulkan
PrimusVK-diagnostic: Creating Vulkan instance
PrimusVK-diagnostic: Device: Intel(R) UHD Graphics 620 (Kabylake GT2)
PrimusVK-diagnostic:  Type: 1
PrimusVK-diagnostic:  API: 1.1.80
PrimusVK-diagnostic:    Queues: 1
PrimusVK-diagnostic: Device: GeForce GTX 1050
PrimusVK-diagnostic:  Type: 2
PrimusVK-diagnostic:  API: 1.0.65
PrimusVK-diagnostic:    Queues: 3
PrimusVK-diagnostic: Device: Intel(R) UHD Graphics 620 (Kabylake GT2)
PrimusVK-diagnostic:  Type: 1
PrimusVK-diagnostic:  API: 1.1.80
PrimusVK-diagnostic:    Queues: 1
PrimusVK-diagnostic: Destroying Vulkan: 0x16352b0
PrimusVK-diagnostic: Loading GL.
PrimusVK-diagnostic: GLX_ARB_get_proc_address GLX_ARB_create_context GLX_ARB_create_context_profile 
PrimusVK-diagnostic: Getting framebuffer config
PrimusVK-diagnostic: Creating window
PrimusVK-diagnostic: Creating context
PrimusVK-diagnostic: Rendering with GL
PrimusVK-diagnostic: Destroying GL context
PrimusVK-diagnostic: Creating Vulkan instance
PrimusVK-diagnostic: Device: Intel(R) UHD Graphics 620 (Kabylake GT2)
PrimusVK-diagnostic:  Type: 1
PrimusVK-diagnostic:  API: 1.1.80
PrimusVK-diagnostic:    Queues: 1
PrimusVK-diagnostic: Device: GeForce GTX 1050
PrimusVK-diagnostic:  Type: 2
PrimusVK-diagnostic:  API: 1.0.65
PrimusVK-diagnostic:    Queues: 3
PrimusVK-diagnostic: Device: Intel(R) UHD Graphics 620 (Kabylake GT2)
PrimusVK-diagnostic:  Type: 1
PrimusVK-diagnostic:  API: 1.1.80
PrimusVK-diagnostic:    Queues: 1
PrimusVK-diagnostic: Destroying Vulkan: 0x17c21e0
```
  
```
$ optirun primus-vk-diag gl vulkan gl
PrimusVK-diagnostic: Loading GL.
PrimusVK-diagnostic: GLX_ARB_get_proc_address GLX_ARB_create_context GLX_ARB_create_context_profile 
PrimusVK-diagnostic: Getting framebuffer config
PrimusVK-diagnostic: Creating window
PrimusVK-diagnostic: Creating context
PrimusVK-diagnostic: Rendering with GL
PrimusVK-diagnostic: Destroying GL context
PrimusVK-diagnostic: Creating Vulkan instance
PrimusVK-diagnostic: Device: Intel(R) UHD Graphics 620 (Kabylake GT2)
PrimusVK-diagnostic:  Type: 1
PrimusVK-diagnostic:  API: 1.1.80
PrimusVK-diagnostic:    Queues: 1
PrimusVK-diagnostic: Device: GeForce GTX 1050
PrimusVK-diagnostic:  Type: 2
PrimusVK-diagnostic:  API: 1.0.65
PrimusVK-diagnostic:    Queues: 3
PrimusVK-diagnostic: Device: Intel(R) UHD Graphics 620 (Kabylake GT2)
PrimusVK-diagnostic:  Type: 1
PrimusVK-diagnostic:  API: 1.1.80
PrimusVK-diagnostic:    Queues: 1
PrimusVK-diagnostic: Destroying Vulkan: 0x27bb180
PrimusVK-diagnostic: Loading GL.
PrimusVK-diagnostic: GLX_ARB_get_proc_address GLX_ARB_create_context GLX_ARB_create_context_profile 
PrimusVK-diagnostic: Getting framebuffer config
PrimusVK-diagnostic: Creating window
PrimusVK-diagnostic: Creating context
PrimusVK-diagnostic: Rendering with GL
PrimusVK-diagnostic: Destroying GL context
```

**Comment by felixdoerre** [comment]
Yup, looks all right. So I guess letting ld.so resolve the library is ok for `libGLX.so`.

**Comment by leonmaxx** [comment]
> but why do add the additional variables `PVK_CXXFLAGS` and `PVK_NV_DRIVER_PATH`? Isn't it enough to add those to `CXXFLAGS` with `+=`?

`Rpmbuild` sets CCFLAGS and CXXFLAGS with distribution suitable compilation flags before entering `%build` section, and yes, it's possible to just `+=` other flags. I'll change that later today.

**Comment by felixdoerre** [comment]
I removed the non-trivial designated initializers from the source code on master, so gcc48.patch should not be needed anymore.

**Comment by leonmaxx** [comment]
Ok, thanks. I'll update scripts soon, had no free time yesterday.

**Comment by rxonda** [comment]
Hello, I'm trying libnv_vulkan_wrapper.so on fedora through the repository, but theres no 32bit on /usr/lib/libnv_vulkan_wrapper.so file. Only the /usr/lib64/libnv_vulkan_wrapper.so.
I wonder if this is the reason for Steam play not work.

**Comment by leonmaxx** [comment]
Hello, to include 32-bit libraries on 64-bit OS you should install like this:
```
dnf install primus-vk primus-vk-libs.i686
```
I'll include install instructions to readme in my repository.

**Comment by rxonda** [comment]
> Hello, to include 32-bit libraries on 64-bit OS you should install like this:
> 
> ```
> dnf install primus-vk primus-vk-libs.i686
> ```
> 
> I'll add install instructions to readme in my repository.

Thanks leonmaxx for your answer.
I tried your instructions but dnf returns no correspondence for primus-vk-libs.i686.
I'm using Fedora 29. I don't know if there's no 32bit libs on version 29.

**Comment by rxonda** [comment]
> @felixdoerre Nope. `primus-vk` and `primus-vk.i686` will have conflicts.
> @rxonda Do you installing from COPR? Or you build package yourself?

I did use COPR

**Comment by leonmaxx** [comment]
Just checked - `primus-vk-libs.i686` package is in repository.
You can download it and install manually from here: https://copr-be.cloud.fedoraproject.org/results/leonmaxx/primus-vk-rpm/fedora-29-i386/00814302-primus-vk/

**Comment by leonmaxx** [comment]
I'm not sure why you not able to install it from repo.

**Comment by rxonda** [comment]
I will try to install the rpm manually.
Should I use the "primus-vk-libs-20181023-1.fc29.i686.rpm"?

**Comment by leonmaxx** [comment]
Yes. If you still can you show us install logs?

**Comment by rxonda** [comment]
@leonmaxx , the library installed and I did succeed to run one step forward the SplinteCell Blacklist on Steam.
It appear a black fullscreen, but the game crashed.
I think the situation is improving.
I will see the logs for why the game crashed.

**Comment by rxonda** [comment]
I think there were some improvement, but had the following problems with the Fedora repo:
- Didn't install the 32bit libraries;
- The nvidia_icd.json file were saved at /etc/vulkan/icd.d/nvidia_icd.json instead of /usr/share/vulkan/icd.d/nvidia_icd.json

**Comment by leonmaxx** [comment]
@rxonda, from what repo you installed nvidia drivers?
